# Matrizes Especiais

matriz transposta: É a matriz que se obtém da troca de linhas por colunas de uma dada matriz.

In [9]:
import numpy as np

In [10]:
matriz_A = np.array([[1,2],[3,4],[5,6]])
matriz_A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
#primeira versão
a_transposta = np.transpose(matriz_A)
a_transposta

array([[1, 3, 5],
       [2, 4, 6]])

ou

In [12]:
#segunda versão
a_transposta_v2 = matriz_A.T
a_transposta_v2

array([[1, 3, 5],
       [2, 4, 6]])

matriz inversa(A⁻¹): É uma matriz que obtida a partir de uma matriz quadrada A, tal que o produto entre A e sua inversa resulta na matriz identidade(I). Além disso, o determinante de A deve ser diferente de 0.

formula= A * A⁻¹ = I

In [17]:
A = np.array([[1, 1, -3], [2, 1, 3], [2, 0, -1]])
A

array([[ 1,  1, -3],
       [ 2,  1,  3],
       [ 2,  0, -1]])

In [18]:
#Descobrindo o determinante
#Determinante diferente de 0, possui matriz inversa
determ = np.linalg.det(A)
determ

13.0

In [20]:
#Calculando inversa da matriz A
A_inversa =  np.linalg.inv(A)
A_inversa

array([[-0.07692308,  0.07692308,  0.46153846],
       [ 0.61538462,  0.38461538, -0.69230769],
       [-0.15384615,  0.15384615, -0.07692308]])

In [22]:
# Calculo da matriz identidade
matriz_identidade = np.dot(A, A_inversa)
matriz_identidade

array([[ 1.00000000e+00, -5.55111512e-17,  5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00,  5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [23]:
B = np.array([[1,-1],[0, 2]])
B

array([[ 1, -1],
       [ 0,  2]])

In [24]:
B_inversa = np.linalg.inv(B)
B

array([[ 1, -1],
       [ 0,  2]])

In [26]:
det = np.linalg.det(B)
det

2.0

In [27]:
m_ident_b = np.dot(B, B_inversa)
m_ident_b

array([[1., 0.],
       [0., 1.]])

In [32]:
#criando matriz identidade, passando por parametro o tamanho da matriz identidade
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
#segunda forma de criar:
I_2 = np.eye(3)
I_2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])