# Determinantes

In [11]:
#import do  numpy
import numpy as np

In [2]:
matriz = np.array([[1, 2, -3],[2, 1, 3], [2, 0, -1]])
matriz

array([[ 1,  2, -3],
       [ 2,  1,  3],
       [ 2,  0, -1]])

In [3]:
det_matriz = np.linalg.det(matriz)
det_matriz

20.99999999999999

In [5]:
matriz_4x4 = np.random.randint(0, 20, size=(4,4))
matriz_4x4

array([[ 1,  0, 17, 14],
       [10, 15,  5, 13],
       [ 7, 15, 17, 10],
       [ 6, 16, 19, 10]])

In [6]:
det_mat_4x4 = np.linalg.det(matriz_4x4)
det_mat_4x4

3681.0000000000005

In [7]:
matriz_3x4 = np.random.randint(0, 10, size=(3,4))
matriz_3x4

array([[7, 6, 9, 1],
       [1, 1, 6, 6],
       [8, 4, 0, 2]])

O bloco de código a seguir causará um erro, pois não se calcula o determinante de uma matriz que não é quadrada. Ou seja, que possui numero de linhas e colunas diferente.

In [8]:
det_mat_3x4 = np.linalg.det(matriz_3x4)
det_mat_3x4

LinAlgError: Last 2 dimensions of the array must be square

### Sistemas de Equações Lineares

In [10]:
# Definição da matriz A e vetor B
A = np.array([[1, 2, 3],[2, 3, 3],[1, 2, 0]])
B = np.array([1, -3, 6])
print(A)
print(B)

[[1 2 3]
 [2 3 3]
 [1 2 0]]
[ 1 -3  6]


A x = B

x = A_inv * B

In [12]:
# Calculo da inversa da matriz A
A_inv = np.linalg.inv(A)
A_inv

array([[-2.        ,  2.        , -1.        ],
       [ 1.        , -1.        ,  1.        ],
       [ 0.33333333, -0.        , -0.33333333]])

In [13]:
# resolução do sistema de equações lineares
x = np.dot(A_inv, B)
x

array([-14.        ,  10.        ,  -1.66666667])

In [14]:
# Resolvendo o sistema de equações lineares de forma direta
x_solve = np.linalg.solve(A, B)
x_solve

array([-14.        ,  10.        ,  -1.66666667])