# Matrizes

no python, matrizes podem ser representadas como uma lista de listas, onde cada lista interna representa uma linha com os elementos da colunas. Exemplo:
lista_matriz = [[1,2,3],[4,5,6]]

In [1]:
matriz_A = [[1, 2, 3], [4, 5, 6]]

In [2]:
matriz_A

[[1, 2, 3], [4, 5, 6]]

acessando itens da matriz

In [8]:
#acesso a primeira linha
matriz_A[0]

[1, 2, 3]

In [9]:
#acesso a segunda linha
matriz_A[1]

[4, 5, 6]

acesso ao valor da primeira linha da terceira coluna

In [10]:
matriz_A[0][2]

3

### introdução ao NumPy
a biblioteca oferece um numero grande de funções e metodos para trabalhar com matrizes multidimensionais

In [11]:
#import do numpy
import numpy as np

dentro do numpy há o metodo array, onde se passa uma lista bidirecional e ele retorna uma matriz

In [12]:
matriz_B = [[96,42,10],[57,86,42], [42,20,56]]

In [17]:
#transoformando o array linear em uma matriz 3x3
matriz_B = np.array(matriz_B)
matriz_B

array([[96, 42, 10],
       [57, 86, 42],
       [42, 20, 56]])

In [18]:
#acessando a segunda linha e segunda coluna
matriz_B[1][1]

86

### Transposição de matriz

transformar as linhas em colunas e colunas em linhas com a função transpose()

In [19]:
matriz_transposta = matriz_B.transpose()
matriz_transposta

array([[96, 57, 42],
       [42, 86, 20],
       [10, 42, 56]])

## Operações com matrizes de Matrizes
só pode ser realizada com matrizes da mesma dimensão

In [20]:
matriz_soma_A = np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz_soma_B = np.array([[9,8,7],[6,5,4],[3,2,1]])
matriz_soma_A + matriz_soma_B

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [21]:
matriz_soma_A - matriz_soma_B

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

multiplicação de matrizes tem regras diferentes. O número de linhas da segunda matriz tem que ser igual ao número de colunas da primeira matriz. Além disso, no python se usa a função dot() da biblioteca NumPy

In [23]:
np.dot(matriz_soma_A, matriz_soma_B)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

## Divisão
Tecnicamente divisão de matrizes não existe